apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_HOSTNAME: keycloak
  KC_DB_URL_DATABASE: keycloak
  KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  KC_HEALTH_ENABLED: true
  KC_HTTP_ENABLED: true
  KC_METRICS_ENABLED: true
  KC_LOG_LEVEL: WARN
  KC_HTTP_RELATIVE_PATH: auth
  # KC_HOSTNAME: keycloak
  # KC_HOSTNAME_PORT: 8180
  #KC_HOSTNAME_URL: http://keycloak.com.au:8180
  #KC_PROXY: reencrypt
  IMP_AUTHORISATION_OPENAPI: http://localhost:8081/*
  IMP_COLLMANAGER_OPENAPI: http://localhost:8080/*
  IMP_EXPLORER_OPENAPI: http://localhost:8082/*
  IMP_DATAWARE_OPENAPI: http://localhost:8085/*
  IMP_FRONT: http://localhost:3000/*






