name: Collection Manager CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  call-template:
    uses: gad-adel/Recolnat-Template/.github/workflows/github-ci-template.yml@main
    with:
      project_ci: collection-manager
    secrets:
      HARBOR_REGISTRY_PASSWORD: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}
      # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    permissions:
      contents: read
